#!/bin/bash
apt-get update && apt-get install -y build-essential cmake mercurial unzip
cd /tmp/plugin/Build
rm -rf AUTOGENERATED

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'
printf "${RED}Don't forget to update the Sources/OrthancExplorer.js file with the correct urls if needed:\n${BLUE}"
sed -n '/var url/p' /tmp/plugin/Sources/OrthancExplorer.js | sed 's/^[ \t]*//'
printf "${NC}\n\n"

cmake .. -DSTATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release
make -j10