name: imaging-hub-local

include:
  - technical-stack.yml
  - keycloak.yml
  - dcm4chee.yml

services:

  # Postgres SQL for Weasis Manager
  weasis-manager-db:
    environment:
      POSTGRES_DB: weasis-manager
      POSTGRES_USER: weasis-manager
      POSTGRES_PASSWORD: weasis-manager

  # Minio for using S3 cloud storage API minio:latest
  minio-storage:
    environment:
      MINIO_ROOT_USER: weasis-manager
      MINIO_ROOT_PASSWORD: weasis-manager
      AWS_ACCESS_KEY_ID: access-key
      AWS_SECRET_ACCESS_KEY: secret-key
    volumes:
      - minio_storage:/resources

  create-bucket:
    image: minio/mc:RELEASE.2024-11-05T11-29-45Z
    container_name: create-s3-bucket
    depends_on:
      - minio-storage
    volumes:
      - ./readwrite-policy.json:/tmp/readwrite-policy.json
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-storage:9000 weasis-manager weasis-manager;
      if ! /usr/bin/mc ls myminio/weasis-manager-bucket >/dev/null 2>&1; then
        /usr/bin/mc mb myminio/weasis-manager-bucket;
        /usr/bin/mc admin policy create myminio readwrite /tmp/readwrite-policy.json;
        /usr/bin/mc admin accesskey create myminio --policy=/tmp/readwrite-policy.json --access-key=access-key --secret-key=secret-key;
      fi &&
      exit 0;
      "

volumes:
  minio_storage:
    name: local_weasis_manager_minio
