name: imaging-hub-local

include:
  - technical-stack.yml
  - keycloak.yml
  - dcm4chee.yml

services:

  # Postgres SQL for Viewer Hub
  viewer-hub-db:
    environment:
      POSTGRES_DB: viewer-hub
      POSTGRES_USER: viewer-hub
      POSTGRES_PASSWORD: viewer-hub

  # Minio for using S3 cloud storage API minio:latest
  minio-storage:
    environment:
      MINIO_ROOT_USER: viewer-hub
      MINIO_ROOT_PASSWORD: viewer-hub
      AWS_ACCESS_KEY_ID: access-key
      AWS_SECRET_ACCESS_KEY: secret-key
    volumes:
      - minio_storage:/resources

  # Nexus to store Weasis bundles (weasis-native.zip)
  nexus:
    volumes:
      - nexus-data:/sonatype-work

  create-bucket:
    image: minio/mc:RELEASE.2024-11-05T11-29-45Z
    container_name: create-s3-bucket
    depends_on:
      - minio-storage
    volumes:
      - ./readwrite-policy.json:/tmp/readwrite-policy.json
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-storage:9000 viewer-hub viewer-hub;
      if ! /usr/bin/mc ls myminio/viewer-hub-bucket >/dev/null 2>&1; then
        /usr/bin/mc mb myminio/viewer-hub-bucket;
        /usr/bin/mc admin policy create myminio readwrite /tmp/readwrite-policy.json;
        /usr/bin/mc admin accesskey create myminio --policy=/tmp/readwrite-policy.json --access-key=access-key --secret-key=secret-key;
      fi &&
      exit 0;
      "

volumes:
  minio_storage:
    name: local_viewer_hub_minio
  nexus-data:
    name: local_viewer_hub_nexus
