version: '3.7'

name: viewer-hub

services:

  # Postgres SQL
  viewer-hub-db:
    image: postgres:17-alpine
    container_name:  viewer-hub_db
    ports:
      - "45101:5432"

  # Redis Cache
  viewer-hub-cache:
    container_name: viewer-hub_cache
    image: redis:7
    ports:
      - "6379:6379"

  # Minio for using S3 cloud storage API minio:latest
  minio-storage:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z
    container_name: viewer-hub_minio
    command: server --console-address ":9090" /resources
    ports:
      - "9080:9000"
      - "9090:9090"

  # Nexus used to store the package versions of Weasis
  nexus:
    image: sonatype/nexus3:3.78.0-alpine
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8086:8081"
      - "8085:8085"

volumes:
  nexus-data:
    name: local_viewer_hub_nexus