# - Viewer Hub
viewer-hub:
  resources-packages:
    # - Prefix used to store objects in S3 bucket: should not start by "/"
    path: resources/packages

#  - Weasis
weasis:
  #  - Weasis package versions
  package:
    version:
      default:
        number: 3.8.2
        qualifier: # example: -MGR