spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: viewer-hub
            client-secret: peLDyVHEpxTQ1A4GZZzQGK5xsPetlTrV
            authorization-grant-type: authorization_code
            redirect-uri: '${BACKEND_URI}/login/oauth2/code/{registrationId}'
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/viewer-hub
            jwk-set-uri: http://localhost:8085/realms/viewer-hub/protocol/openid-connect/certs