#  - Connectors
connector:
  # If value is present: use the connectors specified, if not present or wrong connector ids: use all the connectors
  # defined in the config
  default: dcm4chee-local # connectorId1, connectorId2

  # Connectors configuration
  config:

    # -----------------------
    # ---- DCM4CHEE PACS ----
    # -----------------------
    dcm4chee-local:
      type: DICOM # DB,DICOM,DICOM WEB
      # ------- Search Criteria ----
      search-criteria:
        deactivated: # SOP_INSTANCE_UID, SERIE_INSTANCE_UID, STUDY_INSTANCE_UID, STUDY_ACCESSION_NUMBER, PATIENT_ID
      # ----------   Wado -------------
      # Used to retrieve images from manifest
      wado:
        authentication:
          # Used to force usage of basic authentication parameters to retrieve images (even if request is authenticated)
          force-basic: false
          # If request is authenticated: retrieve the token from the authenticated request and inject it in the manifest for Weasis to get the images
          oauth2:
            # Url used to retrieve images by adding authenticated request token in manifest
            url: http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/wado
          # Retrieve the images by using this basic authentication parameters
          basic:
            # Url used to retrieve images by using basic authentication
            url: http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/wado
            # Basic credentials
            login:
            password:
        transfer-syntax-uid: '*'
      # --------   For dicom ----------
      dicom-connector:
        calling-aet: VIEWER-HUB
        aet: DCM4CHEE
        host: localhost
        port: 11112